MSG_KIND_NORMAL = 'danmaku'
MSG_KIND_GIFT = 'gift'
MSG_KIND_GUARD = 'guard'
MSG_KIND_SUPER_CHAT = 'super-chat'
BODY_ADDON_KEY_ROOM_ID = 'recording_room_id'

DB_COL_PK = '_id'
DB_COL_TIME = '_recv_time'
DB_COL_HASH = '_unique_data_hash'
DB_COL_EX_FIELD = '_extra_fields'
